# Site settings
title: Jareen Imam
email: jareenimam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jareen Imam is a writer and producer for CNN Digital.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jareenimam.io" # the base hostname & protocol for your site
twitter_username: jareenai
github_username: jareenai

# Build settings
markdown: kramdown
